
import "./globals.css";
import Link from "next/link";
import Header from "./header";
import Footer from "./footer";
import { Inter } from 'next/font/google'
// import { Providers } from "./redux/Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
        <title>vloerplaat</title>
      </head>
      <body >

          <Header/>
          <main>
            {children}
          </main>
          <Footer/>

      </body>
    </html>
  );
}